### ISSUE TITLE
Cannot read property type of null

### ISSUE THREAD

**Issue by Spartanace1024** [developmentseed/dirty-reprojectors#11]
When using this command
`cat us-states.geojson | dirty-reproject --forward albersUsa > output.geojson` i'm getting the below error.

```
C:\Users\Thomas\AppData\Roaming\npm\node_modules\dirty-reprojectors\node_modules\turf-meta\index.js:40
    isGeometryCollection = geometryMaybeCollection.type === 'GeometryCollection';
                                                   ^

TypeError: Cannot read property 'type' of null
    at coordEach (C:\Users\Thomas\AppData\Roaming\npm\node_modules\dirty-reprojectors\node_modules\turf-meta\index.js:40:52)
    at module.exports (C:\Users\Thomas\AppData\Roaming\npm\node_modules\dirty-reprojectors\node_modules\turf-extent\index.js:61:5)
    at DestroyableTransform.write [as _transform] (C:\Users\Thomas\AppData\Roaming\npm\node_modules\dirty-reprojectors\bin\dirty-reproject:50:18)
    at DestroyableTransform.Transform._read (C:\Users\Thomas\AppData\Roaming\npm\node_modules\dirty-reprojectors\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (C:\Users\Thomas\AppData\Roaming\npm\node_modules\dirty-reprojectors\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (C:\Users\Thomas\AppData\Roaming\npm\node_modules\dirty-reprojectors\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (C:\Users\Thomas\AppData\Roaming\npm\node_modules\dirty-reprojectors\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (C:\Users\Thomas\AppData\Roaming\npm\node_modules\dirty-reprojectors\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at Stream.ondata (internal/streams/legacy.js:16:26)
    at emitOne (events.js:116:13)
```

**Comment by dereklieu** [comment]
Is `us-states.geojson` a [valid geojson](http://geojsonlint.com/)?

**Comment by brambow** [comment]
@Spartanace1024 I ran into this using States data downloaded from the census.  You may want to check to make sure US Territories aren't included in your input dataset.  The Albers US projection can only handle the 50 States (+DC) so there should only be 51 records in your states table.

**Comment by sinanatra** [comment]
i have the same error when i try to convert a geojson made out of point, is there a way to make it work?

```/usr/local/lib/node_modules/dirty-reprojectors/node_modules/turf-meta/index.js:40
    isGeometryCollection = geometryMaybeCollection.type === 'GeometryCollection';
                                                   ^

TypeError: Cannot read property 'type' of null
    at coordEach (/usr/local/lib/node_modules/dirty-reprojectors/node_modules/turf-meta/index.js:40:52)
    at module.exports (/usr/local/lib/node_modules/dirty-reprojectors/node_modules/turf-extent/index.js:61:5)
    at DestroyableTransform.write [as _transform] (/usr/local/lib/node_modules/dirty-reprojectors/bin/dirty-reproject:50:18)
    at DestroyableTransform.Transform._read (/usr/local/lib/node_modules/dirty-reprojectors/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/usr/local/lib/node_modules/dirty-reprojectors/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/usr/local/lib/node_modules/dirty-reprojectors/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/usr/local/lib/node_modules/dirty-reprojectors/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (/usr/local/lib/node_modules/dirty-reprojectors/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Stream.ondata (internal/streams/legacy.js:15:31)
    at Stream.emit (events.js:189:13)
```

**Comment by dereklieu** [comment]
@sinanatra can you post or link to a sample geojson file that creates this problem?

**Comment by sinanatra** [comment]
@dereklieu  here, https://gist.githubusercontent.com/sinanatra/9bc59d406377f373df6359f6f69d4d8a/raw/c023038ad11cbc5719be071821c4a48c0ed84792/person.geojson 
It happens with every geojson made out of single points. I also tried with the dirty reprojectors app, where it loads the file but exports only the baseline grid

**Comment by dereklieu** [comment]
@sinanatra thanks, I've pushed a new version to NPM and merged a PR in this repo that addresses your issue. The problem was bundling a very old version of `turf-extent` that didn't handle point geometries particularly well.
